import Foundation

struct AquaDotLevelRecord: Hashable, Sendable {
    let originalName: String
    let resourceBaseName: String
    let checksum: UInt16
    let width: Int
    let height: Int
}

enum AquaDotOriginalLevelCatalog {
    static let standardLevels: [AquaDotLevelRecord] = [
        AquaDotLevelRecord(originalName: "Bad Fish (1)", resourceBaseName: "ADL_001_Bad_Fish_1", checksum: 57145, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Bad Fish (2)", resourceBaseName: "ADL_002_Bad_Fish_2", checksum: 9832, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Bad Fish (3)", resourceBaseName: "ADL_003_Bad_Fish_3", checksum: 9334, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Bad Fish (4)", resourceBaseName: "ADL_004_Bad_Fish_4", checksum: 12091, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Bad Fish (5)", resourceBaseName: "ADL_005_Bad_Fish_5", checksum: 15939, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Bolt (1)", resourceBaseName: "ADL_006_Bolt_1", checksum: 23090, width: 37, height: 30),
        AquaDotLevelRecord(originalName: "Bolt (2)", resourceBaseName: "ADL_007_Bolt_2", checksum: 13681, width: 37, height: 30),
        AquaDotLevelRecord(originalName: "Bolt (3)", resourceBaseName: "ADL_008_Bolt_3", checksum: 64009, width: 37, height: 30),
        AquaDotLevelRecord(originalName: "Bolt (4)", resourceBaseName: "ADL_009_Bolt_4", checksum: 41196, width: 37, height: 30),
        AquaDotLevelRecord(originalName: "Bolt (5)", resourceBaseName: "ADL_010_Bolt_5", checksum: 39813, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Chunky (1)", resourceBaseName: "ADL_011_Chunky_1", checksum: 8316, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Chunky (2)", resourceBaseName: "ADL_012_Chunky_2", checksum: 5492, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Chunky (3)", resourceBaseName: "ADL_013_Chunky_3", checksum: 34737, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Chunky (4)", resourceBaseName: "ADL_014_Chunky_4", checksum: 56258, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Chunky (5)", resourceBaseName: "ADL_015_Chunky_5", checksum: 21600, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Combacat (1)", resourceBaseName: "ADL_016_Combacat_1", checksum: 27434, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Combacat (2)", resourceBaseName: "ADL_017_Combacat_2", checksum: 10046, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Combacat (3)", resourceBaseName: "ADL_018_Combacat_3", checksum: 44424, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Combacat (4)", resourceBaseName: "ADL_019_Combacat_4", checksum: 11325, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Combacat (5)", resourceBaseName: "ADL_020_Combacat_5", checksum: 18951, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Dividend (1)", resourceBaseName: "ADL_021_Dividend_1", checksum: 58229, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Dividend (2)", resourceBaseName: "ADL_022_Dividend_2", checksum: 39715, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Dividend (3)", resourceBaseName: "ADL_023_Dividend_3", checksum: 2451, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Dividend (4)", resourceBaseName: "ADL_024_Dividend_4", checksum: 43418, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Dividend (5)", resourceBaseName: "ADL_025_Dividend_5", checksum: 22245, width: 39, height: 28),
        AquaDotLevelRecord(originalName: "Duality (1)", resourceBaseName: "ADL_026_Duality_1", checksum: 54511, width: 27, height: 30),
        AquaDotLevelRecord(originalName: "Duality (2)", resourceBaseName: "ADL_027_Duality_2", checksum: 17998, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Duality (3)", resourceBaseName: "ADL_028_Duality_3", checksum: 18324, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Duality (4)", resourceBaseName: "ADL_029_Duality_4", checksum: 40511, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Duality (5)", resourceBaseName: "ADL_030_Duality_5", checksum: 64985, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Eating Cake (1)", resourceBaseName: "ADL_031_Eating_Cake_1", checksum: 38454, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "Eating Cake (2)", resourceBaseName: "ADL_032_Eating_Cake_2", checksum: 34804, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "Eating Cake (3)", resourceBaseName: "ADL_033_Eating_Cake_3", checksum: 58198, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "Eating Cake (4)", resourceBaseName: "ADL_034_Eating_Cake_4", checksum: 52305, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "Eating Cake (5)", resourceBaseName: "ADL_035_Eating_Cake_5", checksum: 2018, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "Eldorado (1)", resourceBaseName: "ADL_036_Eldorado_1", checksum: 27270, width: 39, height: 26),
        AquaDotLevelRecord(originalName: "Eldorado (2)", resourceBaseName: "ADL_037_Eldorado_2", checksum: 9170, width: 39, height: 26),
        AquaDotLevelRecord(originalName: "Eldorado (3)", resourceBaseName: "ADL_038_Eldorado_3", checksum: 4348, width: 39, height: 26),
        AquaDotLevelRecord(originalName: "Eldorado (4)", resourceBaseName: "ADL_039_Eldorado_4", checksum: 60022, width: 39, height: 24),
        AquaDotLevelRecord(originalName: "Eldorado (5)", resourceBaseName: "ADL_040_Eldorado_5", checksum: 2782, width: 39, height: 24),
        AquaDotLevelRecord(originalName: "Euphoria (1)", resourceBaseName: "ADL_041_Euphoria_1", checksum: 4658, width: 31, height: 30),
        AquaDotLevelRecord(originalName: "Euphoria (2)", resourceBaseName: "ADL_042_Euphoria_2", checksum: 20711, width: 31, height: 30),
        AquaDotLevelRecord(originalName: "Euphoria (3)", resourceBaseName: "ADL_043_Euphoria_3", checksum: 12418, width: 31, height: 30),
        AquaDotLevelRecord(originalName: "Euphoria (4)", resourceBaseName: "ADL_044_Euphoria_4", checksum: 49614, width: 29, height: 30),
        AquaDotLevelRecord(originalName: "Euphoria (5)", resourceBaseName: "ADL_045_Euphoria_5", checksum: 62828, width: 35, height: 30),
        AquaDotLevelRecord(originalName: "Ewe (1)", resourceBaseName: "ADL_046_Ewe_1", checksum: 11464, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Ewe (2)", resourceBaseName: "ADL_047_Ewe_2", checksum: 37615, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Ewe (3)", resourceBaseName: "ADL_048_Ewe_3", checksum: 21962, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Ewe (4)", resourceBaseName: "ADL_049_Ewe_4", checksum: 7381, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Ewe (5)", resourceBaseName: "ADL_050_Ewe_5", checksum: 34745, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Forks (1)", resourceBaseName: "ADL_051_Forks_1", checksum: 44938, width: 31, height: 30),
        AquaDotLevelRecord(originalName: "Forks (2)", resourceBaseName: "ADL_052_Forks_2", checksum: 52707, width: 31, height: 30),
        AquaDotLevelRecord(originalName: "Forks (3)", resourceBaseName: "ADL_053_Forks_3", checksum: 29617, width: 31, height: 30),
        AquaDotLevelRecord(originalName: "Forks (4)", resourceBaseName: "ADL_054_Forks_4", checksum: 825, width: 29, height: 30),
        AquaDotLevelRecord(originalName: "Forks (5)", resourceBaseName: "ADL_055_Forks_5", checksum: 39572, width: 29, height: 30),
        AquaDotLevelRecord(originalName: "Hedges (1)", resourceBaseName: "ADL_056_Hedges_1", checksum: 56492, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Hedges (2)", resourceBaseName: "ADL_057_Hedges_2", checksum: 25375, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Hedges (3)", resourceBaseName: "ADL_058_Hedges_3", checksum: 47918, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Hedges (4)", resourceBaseName: "ADL_059_Hedges_4", checksum: 53836, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Hedges (5)", resourceBaseName: "ADL_060_Hedges_5", checksum: 47359, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Hieroglyph (1)", resourceBaseName: "ADL_061_Hieroglyph_1", checksum: 2041, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Hieroglyph (2)", resourceBaseName: "ADL_062_Hieroglyph_2", checksum: 17955, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Hieroglyph (3)", resourceBaseName: "ADL_063_Hieroglyph_3", checksum: 62769, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Hieroglyph (4)", resourceBaseName: "ADL_064_Hieroglyph_4", checksum: 59123, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Hieroglyph (5)", resourceBaseName: "ADL_065_Hieroglyph_5", checksum: 34049, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Lamon Brown (1)", resourceBaseName: "ADL_066_Lamon_Brown_1", checksum: 41521, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Lamon Brown (2)", resourceBaseName: "ADL_067_Lamon_Brown_2", checksum: 60714, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Lamon Brown (3)", resourceBaseName: "ADL_068_Lamon_Brown_3", checksum: 27024, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Lamon Brown (4)", resourceBaseName: "ADL_069_Lamon_Brown_4", checksum: 47065, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Lamon Brown (5)", resourceBaseName: "ADL_070_Lamon_Brown_5", checksum: 6116, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Masque (1)", resourceBaseName: "ADL_071_Masque_1", checksum: 24789, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Masque (2)", resourceBaseName: "ADL_072_Masque_2", checksum: 27568, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Masque (3)", resourceBaseName: "ADL_073_Masque_3", checksum: 26046, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Masque (4)", resourceBaseName: "ADL_074_Masque_4", checksum: 16959, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Masque (5)", resourceBaseName: "ADL_075_Masque_5", checksum: 33482, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Nines (1)", resourceBaseName: "ADL_076_Nines_1", checksum: 24624, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "Nines (2)", resourceBaseName: "ADL_077_Nines_2", checksum: 13200, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "Nines (3)", resourceBaseName: "ADL_078_Nines_3", checksum: 55344, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "Nines (4)", resourceBaseName: "ADL_079_Nines_4", checksum: 6811, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "Nines (5)", resourceBaseName: "ADL_080_Nines_5", checksum: 15013, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "Panda (1)", resourceBaseName: "ADL_081_Panda_1", checksum: 43647, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Panda (2)", resourceBaseName: "ADL_082_Panda_2", checksum: 54617, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Panda (3)", resourceBaseName: "ADL_083_Panda_3", checksum: 6004, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Panda (4)", resourceBaseName: "ADL_084_Panda_4", checksum: 38465, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Panda (5)", resourceBaseName: "ADL_085_Panda_5", checksum: 37206, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Pods (1)", resourceBaseName: "ADL_086_Pods_1", checksum: 62746, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Pods (2)", resourceBaseName: "ADL_087_Pods_2", checksum: 28684, width: 39, height: 27),
        AquaDotLevelRecord(originalName: "Pods (3)", resourceBaseName: "ADL_088_Pods_3", checksum: 36383, width: 39, height: 27),
        AquaDotLevelRecord(originalName: "Pods (4)", resourceBaseName: "ADL_089_Pods_4", checksum: 3965, width: 39, height: 27),
        AquaDotLevelRecord(originalName: "Pods (5)", resourceBaseName: "ADL_090_Pods_5", checksum: 32133, width: 37, height: 27),
        AquaDotLevelRecord(originalName: "Quadrupeds (1)", resourceBaseName: "ADL_091_Quadrupeds_1", checksum: 34663, width: 34, height: 29),
        AquaDotLevelRecord(originalName: "Quadrupeds (2)", resourceBaseName: "ADL_092_Quadrupeds_2", checksum: 32788, width: 34, height: 29),
        AquaDotLevelRecord(originalName: "Quadrupeds (3)", resourceBaseName: "ADL_093_Quadrupeds_3", checksum: 55508, width: 34, height: 29),
        AquaDotLevelRecord(originalName: "Quadrupeds (4)", resourceBaseName: "ADL_094_Quadrupeds_4", checksum: 12860, width: 34, height: 29),
        AquaDotLevelRecord(originalName: "Quadrupeds (5)", resourceBaseName: "ADL_095_Quadrupeds_5", checksum: 42219, width: 34, height: 29),
        AquaDotLevelRecord(originalName: "Quorum (1)", resourceBaseName: "ADL_096_Quorum_1", checksum: 64785, width: 27, height: 30),
        AquaDotLevelRecord(originalName: "Quorum (2)", resourceBaseName: "ADL_097_Quorum_2", checksum: 7985, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Quorum (3)", resourceBaseName: "ADL_098_Quorum_3", checksum: 42104, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Quorum (4)", resourceBaseName: "ADL_099_Quorum_4", checksum: 63019, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Quorum (5)", resourceBaseName: "ADL_100_Quorum_5", checksum: 38789, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Repeat (1)", resourceBaseName: "ADL_101_Repeat_1", checksum: 14962, width: 39, height: 28),
        AquaDotLevelRecord(originalName: "Repeat (2)", resourceBaseName: "ADL_102_Repeat_2", checksum: 55632, width: 39, height: 28),
        AquaDotLevelRecord(originalName: "Repeat (3)", resourceBaseName: "ADL_103_Repeat_3", checksum: 10509, width: 39, height: 28),
        AquaDotLevelRecord(originalName: "Repeat (4)", resourceBaseName: "ADL_104_Repeat_4", checksum: 67, width: 39, height: 28),
        AquaDotLevelRecord(originalName: "Repeat (5)", resourceBaseName: "ADL_105_Repeat_5", checksum: 3085, width: 39, height: 28),
        AquaDotLevelRecord(originalName: "Right Wing (1)", resourceBaseName: "ADL_106_Right_Wing_1", checksum: 37918, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Right Wing (2)", resourceBaseName: "ADL_107_Right_Wing_2", checksum: 33728, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Right Wing (3)", resourceBaseName: "ADL_108_Right_Wing_3", checksum: 7137, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Right Wing (4)", resourceBaseName: "ADL_109_Right_Wing_4", checksum: 63455, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Right Wing (5)", resourceBaseName: "ADL_110_Right_Wing_5", checksum: 62499, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Scorch (1)", resourceBaseName: "ADL_111_Scorch_1", checksum: 32555, width: 37, height: 30),
        AquaDotLevelRecord(originalName: "Scorch (2)", resourceBaseName: "ADL_112_Scorch_2", checksum: 31996, width: 37, height: 30),
        AquaDotLevelRecord(originalName: "Scorch (3)", resourceBaseName: "ADL_113_Scorch_3", checksum: 26851, width: 37, height: 30),
        AquaDotLevelRecord(originalName: "Scorch (4)", resourceBaseName: "ADL_114_Scorch_4", checksum: 4540, width: 37, height: 30),
        AquaDotLevelRecord(originalName: "Scorch (5)", resourceBaseName: "ADL_115_Scorch_5", checksum: 36384, width: 37, height: 30),
        AquaDotLevelRecord(originalName: "Serengeti (1)", resourceBaseName: "ADL_116_Serengeti_1", checksum: 60789, width: 40, height: 25),
        AquaDotLevelRecord(originalName: "Serengeti (2)", resourceBaseName: "ADL_117_Serengeti_2", checksum: 64313, width: 40, height: 25),
        AquaDotLevelRecord(originalName: "Serengeti (3)", resourceBaseName: "ADL_118_Serengeti_3", checksum: 1163, width: 40, height: 25),
        AquaDotLevelRecord(originalName: "Serengeti (4)", resourceBaseName: "ADL_119_Serengeti_4", checksum: 58312, width: 40, height: 25),
        AquaDotLevelRecord(originalName: "Serengeti (5)", resourceBaseName: "ADL_120_Serengeti_5", checksum: 447, width: 40, height: 25),
        AquaDotLevelRecord(originalName: "Singularity (1)", resourceBaseName: "ADL_121_Singularity_1", checksum: 41016, width: 27, height: 30),
        AquaDotLevelRecord(originalName: "Singularity (2)", resourceBaseName: "ADL_122_Singularity_2", checksum: 21577, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Singularity (3)", resourceBaseName: "ADL_123_Singularity_3", checksum: 37356, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "Singularity (4)", resourceBaseName: "ADL_124_Singularity_4", checksum: 10867, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "Singularity (5)", resourceBaseName: "ADL_125_Singularity_5", checksum: 36853, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "Skyscrapers (1)", resourceBaseName: "ADL_126_Skyscrapers_1", checksum: 63211, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Skyscrapers (2)", resourceBaseName: "ADL_127_Skyscrapers_2", checksum: 58789, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Skyscrapers (3)", resourceBaseName: "ADL_128_Skyscrapers_3", checksum: 19299, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Skyscrapers (4)", resourceBaseName: "ADL_129_Skyscrapers_4", checksum: 11331, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Skyscrapers (5)", resourceBaseName: "ADL_130_Skyscrapers_5", checksum: 24115, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Sliced (1)", resourceBaseName: "ADL_131_Sliced_1", checksum: 27007, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Sliced (2)", resourceBaseName: "ADL_132_Sliced_2", checksum: 18440, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Sliced (3)", resourceBaseName: "ADL_133_Sliced_3", checksum: 64183, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Sliced (4)", resourceBaseName: "ADL_134_Sliced_4", checksum: 9715, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Sliced (5)", resourceBaseName: "ADL_135_Sliced_5", checksum: 45229, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Snails (1)", resourceBaseName: "ADL_136_Snails_1", checksum: 28576, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Snails (2)", resourceBaseName: "ADL_137_Snails_2", checksum: 24668, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Snails (3)", resourceBaseName: "ADL_138_Snails_3", checksum: 58888, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Snails (4)", resourceBaseName: "ADL_139_Snails_4", checksum: 36320, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Snails (5)", resourceBaseName: "ADL_140_Snails_5", checksum: 59614, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Spaz (1)", resourceBaseName: "ADL_141_Spaz_1", checksum: 26666, width: 38, height: 29),
        AquaDotLevelRecord(originalName: "Spaz (2)", resourceBaseName: "ADL_142_Spaz_2", checksum: 8701, width: 38, height: 29),
        AquaDotLevelRecord(originalName: "Spaz (3)", resourceBaseName: "ADL_143_Spaz_3", checksum: 62780, width: 38, height: 29),
        AquaDotLevelRecord(originalName: "Spaz (4)", resourceBaseName: "ADL_144_Spaz_4", checksum: 60982, width: 38, height: 29),
        AquaDotLevelRecord(originalName: "Spaz (5)", resourceBaseName: "ADL_145_Spaz_5", checksum: 23954, width: 38, height: 29),
        AquaDotLevelRecord(originalName: "Spider (1)", resourceBaseName: "ADL_146_Spider_1", checksum: 38584, width: 40, height: 27),
        AquaDotLevelRecord(originalName: "Spider (2)", resourceBaseName: "ADL_147_Spider_2", checksum: 59892, width: 40, height: 27),
        AquaDotLevelRecord(originalName: "Spider (3)", resourceBaseName: "ADL_148_Spider_3", checksum: 22415, width: 40, height: 25),
        AquaDotLevelRecord(originalName: "Spider (4)", resourceBaseName: "ADL_149_Spider_4", checksum: 58008, width: 40, height: 25),
        AquaDotLevelRecord(originalName: "Spider (5)", resourceBaseName: "ADL_150_Spider_5", checksum: 42455, width: 40, height: 25),
        AquaDotLevelRecord(originalName: "Splitsville (1)", resourceBaseName: "ADL_151_Splitsville_1", checksum: 20968, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Splitsville (2)", resourceBaseName: "ADL_152_Splitsville_2", checksum: 63632, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Splitsville (3)", resourceBaseName: "ADL_153_Splitsville_3", checksum: 40949, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Splitsville (4)", resourceBaseName: "ADL_154_Splitsville_4", checksum: 5466, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Splitsville (5)", resourceBaseName: "ADL_155_Splitsville_5", checksum: 55807, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Squirrel (1)", resourceBaseName: "ADL_156_Squirrel_1", checksum: 37070, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Squirrel (2)", resourceBaseName: "ADL_157_Squirrel_2", checksum: 58913, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Squirrel (3)", resourceBaseName: "ADL_158_Squirrel_3", checksum: 31448, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Squirrel (4)", resourceBaseName: "ADL_159_Squirrel_4", checksum: 10067, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Squirrel (5)", resourceBaseName: "ADL_160_Squirrel_5", checksum: 60623, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "StreetSmarts (1)", resourceBaseName: "ADL_161_StreetSmarts_1", checksum: 1832, width: 35, height: 28),
        AquaDotLevelRecord(originalName: "StreetSmarts (2)", resourceBaseName: "ADL_162_StreetSmarts_2", checksum: 50429, width: 35, height: 28),
        AquaDotLevelRecord(originalName: "StreetSmarts (3)", resourceBaseName: "ADL_163_StreetSmarts_3", checksum: 36991, width: 35, height: 28),
        AquaDotLevelRecord(originalName: "StreetSmarts (4)", resourceBaseName: "ADL_164_StreetSmarts_4", checksum: 35339, width: 35, height: 28),
        AquaDotLevelRecord(originalName: "StreetSmarts (5)", resourceBaseName: "ADL_165_StreetSmarts_5", checksum: 6568, width: 35, height: 28),
        AquaDotLevelRecord(originalName: "Swervel (1)", resourceBaseName: "ADL_166_Swervel_1", checksum: 20426, width: 38, height: 29),
        AquaDotLevelRecord(originalName: "Swervel (2)", resourceBaseName: "ADL_167_Swervel_2", checksum: 24853, width: 38, height: 29),
        AquaDotLevelRecord(originalName: "Swervel (3)", resourceBaseName: "ADL_168_Swervel_3", checksum: 58327, width: 38, height: 29),
        AquaDotLevelRecord(originalName: "Swervel (4)", resourceBaseName: "ADL_169_Swervel_4", checksum: 34367, width: 38, height: 29),
        AquaDotLevelRecord(originalName: "Swervel (5)", resourceBaseName: "ADL_170_Swervel_5", checksum: 42791, width: 38, height: 29),
        AquaDotLevelRecord(originalName: "Tempest (1)", resourceBaseName: "ADL_171_Tempest_1", checksum: 47064, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Tempest (2)", resourceBaseName: "ADL_172_Tempest_2", checksum: 38065, width: 39, height: 28),
        AquaDotLevelRecord(originalName: "Tempest (3)", resourceBaseName: "ADL_173_Tempest_3", checksum: 64498, width: 39, height: 28),
        AquaDotLevelRecord(originalName: "Tempest (4)", resourceBaseName: "ADL_174_Tempest_4", checksum: 23364, width: 39, height: 28),
        AquaDotLevelRecord(originalName: "Tempest (5)", resourceBaseName: "ADL_175_Tempest_5", checksum: 8758, width: 39, height: 28),
        AquaDotLevelRecord(originalName: "Tensor (1)", resourceBaseName: "ADL_176_Tensor_1", checksum: 5596, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Tensor (2)", resourceBaseName: "ADL_177_Tensor_2", checksum: 54637, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Tensor (3)", resourceBaseName: "ADL_178_Tensor_3", checksum: 57281, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Tensor (4)", resourceBaseName: "ADL_179_Tensor_4", checksum: 28746, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Tensor (5)", resourceBaseName: "ADL_180_Tensor_5", checksum: 14419, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Tertiary (1)", resourceBaseName: "ADL_181_Tertiary_1", checksum: 40012, width: 29, height: 30),
        AquaDotLevelRecord(originalName: "Tertiary (2)", resourceBaseName: "ADL_182_Tertiary_2", checksum: 43342, width: 33, height: 30),
        AquaDotLevelRecord(originalName: "Tertiary (3)", resourceBaseName: "ADL_183_Tertiary_3", checksum: 7842, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Tertiary (4)", resourceBaseName: "ADL_184_Tertiary_4", checksum: 11301, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Tertiary (5)", resourceBaseName: "ADL_185_Tertiary_5", checksum: 17193, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Trio (1)", resourceBaseName: "ADL_186_Trio_1", checksum: 61138, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Trio (2)", resourceBaseName: "ADL_187_Trio_2", checksum: 47637, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Trio (3)", resourceBaseName: "ADL_188_Trio_3", checksum: 754, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Trio (4)", resourceBaseName: "ADL_189_Trio_4", checksum: 37194, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Trio (5)", resourceBaseName: "ADL_190_Trio_5", checksum: 13963, width: 40, height: 30),
        AquaDotLevelRecord(originalName: "Voodoo (1)", resourceBaseName: "ADL_191_Voodoo_1", checksum: 23507, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Voodoo (2)", resourceBaseName: "ADL_192_Voodoo_2", checksum: 26280, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Voodoo (3)", resourceBaseName: "ADL_193_Voodoo_3", checksum: 28841, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Voodoo (4)", resourceBaseName: "ADL_194_Voodoo_4", checksum: 24360, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "Voodoo (5)", resourceBaseName: "ADL_195_Voodoo_5", checksum: 2572, width: 39, height: 30),
        AquaDotLevelRecord(originalName: "XrixxXroxx (1)", resourceBaseName: "ADL_196_XrixxXroxx_1", checksum: 48864, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "XrixxXroxx (2)", resourceBaseName: "ADL_197_XrixxXroxx_2", checksum: 30394, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "XrixxXroxx (3)", resourceBaseName: "ADL_198_XrixxXroxx_3", checksum: 18471, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "XrixxXroxx (4)", resourceBaseName: "ADL_199_XrixxXroxx_4", checksum: 1312, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "XrixxXroxx (5)", resourceBaseName: "ADL_200_XrixxXroxx_5", checksum: 40156, width: 40, height: 29),
        AquaDotLevelRecord(originalName: "Zephyr (1)", resourceBaseName: "ADL_201_Zephyr_1", checksum: 15141, width: 37, height: 29),
        AquaDotLevelRecord(originalName: "Zephyr (2)", resourceBaseName: "ADL_202_Zephyr_2", checksum: 64358, width: 37, height: 29),
        AquaDotLevelRecord(originalName: "Zephyr (3)", resourceBaseName: "ADL_203_Zephyr_3", checksum: 2064, width: 37, height: 29),
        AquaDotLevelRecord(originalName: "Zephyr (4)", resourceBaseName: "ADL_204_Zephyr_4", checksum: 46278, width: 37, height: 29),
        AquaDotLevelRecord(originalName: "Zephyr (5)", resourceBaseName: "ADL_205_Zephyr_5", checksum: 58448, width: 39, height: 29),
    ]

    static func record(named originalName: String) -> AquaDotLevelRecord? {
        standardLevels.first { $0.originalName == originalName }
    }
}
